# Scale ×4
inherit: configs/common.yml

data:
  hr_size: 512
  scale: 4

train:
  epochs: 1800

optim:
  lr: 0.0007

model:
  d_model: 96
  n_heads: 6            # 96 / 6 = 16
  mlp_hidden: 192
  num_rank_tokens: 16
  fourier_K: 12
  alpha_init: 0.05
  alpha_min: 0.02
